services:
  - type: web
    name: crm-api
    env: node
    plan: free
    region: virginia
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false   # La vas a agregar manual en Render UI
